const DEFAULTS={backendEndpoint:'http://127.0.0.1:8765/api/discussion-lab/run',resultPage:'http://127.0.0.1:8765/discussion-lab',model:'gpt-5.6',reasoning_effort:'low',max_output_tokens:12000,timeout:180000,floatingEnabled:true};
chrome.runtime.onInstalled.addListener(()=>{chrome.storage.local.get(DEFAULTS,x=>chrome.storage.local.set(x));try{chrome.contextMenus.create({id:'vrg-audit',title:'Analyze with STRING',contexts:['selection']})}catch(_){ }});
chrome.action.onClicked.addListener(tab=>chrome.sidePanel.open({windowId:tab.windowId}));
chrome.contextMenus.onClicked.addListener((info,tab)=>{if(info.menuItemId==='vrg-audit')saveCapture({selectedText:info.selectionText,title:tab?.title,url:tab?.url,mode:'context_menu'},tab)});
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message?.type==='CAPTURE_SELECTION'||message?.type==='CAPTURE'){saveCapture(message.payload||message,sender.tab).then(sendResponse);return true}if(message?.type==='CAPTURE_ACTIVE_TAB'){captureSelectionFromActiveTab().then(sendResponse);return true}if(message?.type==='SEND_TO_BACKEND'){run(message.payload).then(sendResponse);return true}return false});
function captureId(){try{return crypto.randomUUID()}catch(_){return `capture_${Date.now()}_${Math.random().toString(36).slice(2,10)}`}}
function emptyCapture(){return {captureId:'',selectedText:'',title:'',url:'',mode:'unknown',capturedAt:'',selectedTextLength:0}}
function normalizeCapture(value){const x={...emptyCapture(),...(value||{})};x.selectedText=String(x.selectedText??x.text??'').trim();x.captureId=String(x.captureId||captureId());x.mode=String(x.mode||'unknown');x.capturedAt=String(x.capturedAt||new Date().toISOString());x.selectedTextLength=x.selectedText.length;return x}
function sanitizeCapture(value){const x=normalizeCapture(value);return {...x,title:String(x.title||'').slice(0,500),url:String(x.url||'').slice(0,2000),selectedText:x.selectedText.slice(0,100000)}}
async function saveCapture(value,tab){const capture=sanitizeCapture({...value,title:value?.title||tab?.title,url:value?.url||tab?.url});if(!capture.selectedText)return {ok:false,error:'선택한 텍스트가 없습니다.'};await chrome.storage.session.set({pendingCapture:capture});console.info('[STRING] capture saved',`captureId=${capture.captureId}`,`mode=${capture.mode}`,`length=${capture.selectedTextLength}`);if(tab?.windowId){try{await chrome.sidePanel.open({windowId:tab.windowId})}catch(error){console.warn('[STRING] side panel open failed',error)}}chrome.runtime.sendMessage({type:'CAPTURE_READY',payload:capture}).catch(()=>{});return {ok:true,payload:capture}}
async function captureSelectionFromActiveTab(){try{const tabs=await chrome.tabs.query({active:true,currentWindow:true});const tab=tabs[0];if(!tab?.id)return {ok:false};const response=await chrome.tabs.sendMessage(tab.id,{type:'GET_SELECTION'});if(response?.ok)return saveCapture(response.payload,tab)}catch(_){}return {ok:false}}
async function run(p){const cfg=await chrome.storage.local.get(DEFAULTS),body={text:p.text,model:p.model||cfg.model,reasoning_effort:p.reasoning_effort||cfg.reasoning_effort,max_output_tokens:clamp(p.max_output_tokens||cfg.max_output_tokens,256,100000),custom_instruction:p.custom_instruction||''};const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),Number(cfg.timeout)||180000);try{const r=await fetch(p.endpoint||cfg.backendEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:ctrl.signal}),x=await r.json().catch(()=>null);if(!r.ok)throw new Error(x?.detail||`HTTP ${r.status}`);const runId=x?.run_id||x?.runId||x?.id||x?.result?.run_id;if(!runId)throw new Error('응답에 run_id가 없습니다.');return {ok:true,status:r.status,requestBody:body,analysisResult:x,runId,resultUrl:`${cfg.resultPage}?run_id=${encodeURIComponent(runId)}`}}catch(e){return {ok:false,error:e.name==='AbortError'?'백엔드 요청 시간 초과':e.message}}finally{clearTimeout(timer)}}
function clamp(v,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.round(n))):min}
