const $=id=>document.getElementById(id);
const defaults={model:'gpt-5.6',reasoning_effort:'low',max_output_tokens:12000};
const state={capture:emptyCapture(),isTextDirty:false,lastRenderedCaptureId:''};
function emptyCapture(){return {captureId:'',selectedText:'',title:'',url:'',mode:'unknown',capturedAt:'',selectedTextLength:0}}
function normalizeCapture(value){const x={...emptyCapture(),...(value||{})};x.selectedText=String(x.selectedText??x.text??'').trim();x.captureId=String(x.captureId||'');x.selectedTextLength=x.selectedText.length;return x}
function setStatus(type,message){$('status').dataset.state=type;$('status').textContent=message}
function renderCapture(){const c=state.capture;if(!c.selectedText||c.captureId===state.lastRenderedCaptureId)return false;$('textInput').value=c.selectedText;state.lastRenderedCaptureId=c.captureId;state.isTextDirty=false;return true}
async function loadPendingCapture(){const stored=await chrome.storage.session.get('pendingCapture');const c=normalizeCapture(stored.pendingCapture);if(!c.selectedText)return false;state.capture=c;return renderCapture()}
async function captureSelectionFromActiveTab(){const response=await chrome.runtime.sendMessage({type:'CAPTURE_ACTIVE_TAB'});if(response?.ok&&response.payload){state.capture=normalizeCapture(response.payload);return renderCapture()}return false}
function legacyCopyText(text){const textarea=document.createElement('textarea');textarea.value=text;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.opacity='0';document.body.appendChild(textarea);textarea.select();const ok=document.execCommand('copy');textarea.remove();if(!ok)throw new Error('copy command was rejected')}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch(_){legacyCopyText(text)}}
async function pasteText(){try{const text=await navigator.clipboard.readText();if(text){$('textInput').focus();const start=$('textInput').selectionStart,end=$('textInput').selectionEnd;$('textInput').setRangeText(text,start,end,'end');state.isTextDirty=true;setStatus('success','Clipboard text inserted.')}}catch(_){$('textInput').focus();setStatus('error','Clipboard auto-read was blocked. Press Ctrl+V in the input field.')}}
async function init(){const c=await chrome.storage.local.get(defaults);$('model').value=c.model;$('effort').value=c.reasoning_effort;$('tokens').value=c.max_output_tokens;const loaded=await loadPendingCapture();if(!loaded)await captureSelectionFromActiveTab();if(!state.capture.selectedText)setStatus('idle','Select text on a webpage, or use the clipboard button for PDF pages.')}
chrome.runtime.onMessage.addListener(message=>{if(message?.type!=='CAPTURE_READY')return;const incoming=normalizeCapture(message.payload);if(!incoming.selectedText||incoming.captureId===state.capture.captureId)return;state.capture=incoming;renderCapture();setStatus('success','New selection loaded.')});
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='session'||!changes.pendingCapture?.newValue)return;const incoming=normalizeCapture(changes.pendingCapture.newValue);if(!incoming.selectedText||incoming.captureId===state.capture.captureId)return;if(state.isTextDirty)return;state.capture=incoming;renderCapture();setStatus('success','New selection loaded.')});
$('textInput').addEventListener('input',()=>{state.isTextDirty=true});
$('options').onclick=()=>chrome.runtime.openOptionsPage();
$('paste').onclick=pasteText;
$('copy').onclick=async()=>{const text=$('textInput').value;if(!text){setStatus('error','There is no text to copy.');return}try{await copyText(text);setStatus('success','Input copied to clipboard.')}catch(error){setStatus('error',error.message)}};
$('run').onclick=async()=>{const text=$('textInput').value.trim();if(!text){setStatus('error','Enter or select text before running the audit.');$('textInput').focus();return}$('run').disabled=true;setStatus('loading','Analyzing…');$('result').hidden=true;const x=await chrome.runtime.sendMessage({type:'SEND_TO_BACKEND',payload:{text,model:$('model').value,reasoning_effort:$('effort').value,max_output_tokens:$('tokens').value,custom_instruction:$('contextInput').value}});$('json').textContent=JSON.stringify(x.analysisResult||x,null,2);$('result').hidden=false;if(x.ok){setStatus('success',`Analysis complete · ${x.runId}`);$('open').href=x.resultUrl;$('open').hidden=false}else{setStatus('error',`Analysis failed · ${x.error}`)}$('run').disabled=false};
init();
